apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base/namespaces/
- ../../base/rbac/
- ../../base/network-policies/

namespace: production

patchesStrategicMerge:
- patch-production.yaml                 # Production hardening

configMapGenerator:
- name: prod-config
  literals:
  - LOG_LEVEL=warn
  - FEATURE_FLAGS=core-only
